### ISSUE TITLE
Connect to iTunes screen

### ISSUE THREAD

**Issue by cybser** [adrianjagielak/icloud-12.5.1-bypass#4]
Hi Adrian,

After the first bypass, iTunes on my MacBook does allow me to configure my iPad as a "new" iPad. The iPad itself just stays stuck on the "Connect to iTunes" screen. I'm running on 12.5.3, perhaps this might be the reason? Thank you.

**Comment by adrianjagielak** [comment]
The 12.5.3 should be working fine (I haven't tested it yet) but if you failed just restore your iPad with the latest .ipsw and try again exactly as its told in the script.

(there might be a small chance of iTunes failure that i haven't identified why it sometimes fails, I myself noticed as I tested it on few phones if it fails on the iTunes script just restore the .ipsw (might not even be necessary, I just did it to be sure) and eventually after 2 or 3 tries every iDevice gets activated fine:) Then if its activated using the first script and you rebooted the second script to activate after reboots works every time)

Let me know if you succeeded!

**Comment by cybser** [comment]
Hi Adrian,

I tried it a few more times, but never got it to work. I instead used Sliver using the iOS14 bypass, strangely enough this also worked on 12.5.3. But not immediately though, I noticed a problem installing libimobiledevice so after fixing that I finally bypassed the iCloud lock using Sliver. I haven't tried using your script after I succeeded, but might be worth checking it out.
